SPIREX-102 Implement workload Registrar for Sigstore on Webhook
HewlettPackard/k8s-sigstore-attestor pull request #13
Opened 2021-12-01 02:21 UTC by willallves

2022-01-25 14:42 UTC, tjamir requested changes
The changes done here are fine. Howerver I think we are missing those points:
- Update documentation with new hcl properties
- Unit test when enabling `check_signature_enabled`

2022-01-26 18:01 UTC, rodrigolc requested changes

2022-01-26 19:22 UTC, tjamir approved these changes

2022-01-27 19:45 UTC, rodrigolc approved these changes

2022-01-27 19:56 UTC, merged