Image skiplist support
HewlettPackard/k8s-sigstore-attestor pull request #18
Opened 2022-01-12 11:57 UTC by rodrigolc

**Pull Request check list**

- [ ] Commit conforms to CONTRIBUTING.md?
- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**

**Description of change**

**Which issue this PR fixes**

2022-01-20 14:20 UTC, tjamir requested changes
There are some points do address, and some we could discuss.

2022-01-20 14:20 UTC, tjamir commented on pkg/agent/plugin/workloadattestor/k8s/k8s.go
> +						selectors = append(selectors, "signature-verified:true")
Same as above

2022-01-20 14:20 UTC, tjamir commented on pkg/agent/plugin/workloadattestor/k8s/k8s.go
> +						selectors = append(selectors, "signature-verified:true")
I think we could hide sigstore details by putting this code block into sigstore and creating a function that encapsulates the fetch and extraction of the selectors.

2022-01-20 14:20 UTC, tjamir commented on pkg/agent/plugin/workloadattestor/k8s/sigstore/sigstore.go
> +	ExtractSelectorsFromSignatures(signatures []oci.Signature) []string
We could hide details such oci.Signature from the interface 
Also, I would put a rekorURL as an attribute from Sigstoreimpl. This way, we could abstract this is Sigstore, intead, I would call this interface SignatureChecker. So that, we could add some other implementations in a future.

2022-01-20 14:20 UTC, tjamir commented on pkg/agent/plugin/workloadattestor/k8s/sigstore/sigstore.go
> +	// TODO: add flag for verified stuff?
Is this TODO already addressed?

2022-01-21 17:40 UTC, rodrigolc commented on pkg/agent/plugin/workloadattestor/k8s/sigstore/sigstore.go
> +	ExtractSelectorsFromSignatures(signatures []oci.Signature) []string
Good idea. I'll draft a new PR and work on it over there.

2022-01-21 17:43 UTC, rodrigolc commented on pkg/agent/plugin/workloadattestor/k8s/sigstore/sigstore.go
> +	// TODO: add flag for verified stuff?
This was left from another idea I had, I'll remove this comment.

2022-01-21 17:46 UTC, rodrigolc commented on pkg/agent/plugin/workloadattestor/k8s/k8s.go
> +					selectors = append(selectors, "signature-verified:true")
Fair enough, I'll update the PR with this change.

2022-01-21 18:02 UTC, rodrigolc commented on pkg/agent/plugin/workloadattestor/k8s/sigstore/sigstore.go
> +	ExtractSelectorsFromSignatures(signatures []oci.Signature) []string
This will be worked on at #21

2022-01-21 18:03 UTC, rodrigolc commented on pkg/agent/plugin/workloadattestor/k8s/k8s.go
> +					selectors = append(selectors, "signature-verified:true")
On second thought, this would be better discussed over the refactoring PR at #21.

2022-01-21 18:06 UTC, rodrigolc commented on pkg/agent/plugin/workloadattestor/k8s/k8s.go
> +						selectors = append(selectors, "signature-verified:true")
I'll bundle this with the other changes meant to encapsulate this bit of logic. see #21

2022-01-25 12:49 UTC, tjamir requested changes
Some minor changes

2022-01-25 12:49 UTC, tjamir commented on pkg/agent/plugin/workloadattestor/k8s/sigstore/sigstore.go
> +
```suggestion
// Validates if the image hash matches with its actual binary content
```

2022-01-25 12:49 UTC, tjamir commented on pkg/agent/plugin/workloadattestor/k8s/sigstore/sigstore.go
> +func (sigstore *Sigstoreimpl) SkipImage(status corev1.ContainerStatus) (bool, error) {
I would rename this function, to something like "ShouldSkipImage" or "IsImageSkipped". Looking for the function name, it seems that this function is going to skip the image, but it actually checks if the images should be skipped.

2022-01-25 13:56 UTC, willallves approved these changes

2022-01-25 14:29 UTC, rodrigolc commented on pkg/agent/plugin/workloadattestor/k8s/sigstore/sigstore.go
> +func (sigstore *Sigstoreimpl) SkipImage(status corev1.ContainerStatus) (bool, error) {
Fair enough, I've changed this.

2022-01-25 15:39 UTC, willallves commented on pkg/agent/plugin/workloadattestor/k8s/k8s_test.go
> +func (s *SigstoreMock) SetSkipSigs(allow bool) {
These methods (Set*) have no calls?

2022-01-25 17:27 UTC, rodrigolc commented on pkg/agent/plugin/workloadattestor/k8s/k8s_test.go
> +func (s *SigstoreMock) SetSkipSigs(allow bool) {
You're right, I've removed those. I preemptively created those thinking I'd use them later, but didn't.

2022-01-26 19:27 UTC, tjamir approved these changes

2022-01-26 19:28 UTC, merged