SPIREX-86 Implement a cache strategy for storing signature
HewlettPackard/k8s-sigstore-attestor pull request #28
Opened 2022-04-05 21:48 UTC by willallves

2022-04-08 11:44 UTC, tjamir requested changes

2022-04-08 11:44 UTC, tjamir commented on pkg/agent/plugin/workloadattestor/k8s/sigstorecache/sigstorecache.go
> +	maximumAmountCache = 3
I would use a greater default value. Maybe 10 or 20?

2022-04-08 11:44 UTC, tjamir commented on pkg/agent/plugin/workloadattestor/k8s/sigstorecache/sigstorecache.go
> +	//mutex sync.RWMutex
```suggestion
	// mutex sync.RWMutex
```

2022-04-08 11:44 UTC, tjamir commented on pkg/agent/plugin/workloadattestor/k8s/sigstorecache/sigstorecache.go
> +	//mutex sync.RWMutex
Or remove this line.

2022-04-08 11:44 UTC, tjamir commented on pkg/agent/plugin/workloadattestor/k8s/sigstorecache/sigstorecache.go
> +		//mutex: sync.RWMutex{},
Same here, add space (due to lint reasons) or remove this line

2022-04-08 11:44 UTC, tjamir commented on pkg/agent/plugin/workloadattestor/k8s/sigstorecache/sigstorecache_test.go
> +			want: cacheMemory.GetSignature(item1.Key),
I don't think this is the right way to do it. We are using the function under test in the "want" field. We should use a variable or constant here. I think we could use `item1.Value` here.

2022-04-08 11:44 UTC, tjamir commented on pkg/agent/plugin/workloadattestor/k8s/sigstorecache/sigstorecache_test.go
> +			c.PutSignature(tt.args.i)
We should add some kind of verification here, to check If the element put here was really put in the cache.

2022-04-11 02:59 UTC, tjamir requested changes
There are some changes proposed here. As a suggestion, I submited a PR for this branch addressing the changes I propose here.

2022-04-11 02:59 UTC, tjamir commented on pkg/agent/plugin/workloadattestor/k8s/sigstorecache/sigstorecache.go
> +	}
I think using a map here should be a better option for performance purposes

2022-04-11 02:59 UTC, tjamir commented on pkg/agent/plugin/workloadattestor/k8s/sigstorecache/sigstorecache.go
> +		c.items.Remove(c.items.Back())
Shouldn't be `c.items.Remove(e)` here?

2022-04-11 02:59 UTC, tjamir commented on pkg/agent/plugin/workloadattestor/k8s/sigstorecache/sigstorecache_test.go
> +	}
To improve readability, we could declare those items in the begining of this file.

2022-04-11 02:59 UTC, tjamir commented on pkg/agent/plugin/workloadattestor/k8s/sigstorecache/sigstorecache_test.go
> +	}
We could use the same standard as other files here.

2022-04-11 02:59 UTC, tjamir commented on pkg/agent/plugin/workloadattestor/k8s/sigstorecache/sigstorecache_test.go
> +	}
Same as above. We could reuse those variables declarations.

2022-04-11 02:59 UTC, tjamir commented on pkg/agent/plugin/workloadattestor/k8s/sigstorecache/sigstorecache_test.go
> +	}
We could use the same standard as other files here.

2022-04-12 17:45 UTC, matheusdefarias approved these changes

2022-04-12 18:20 UTC, merged