Sigstore crd
HewlettPackard/k8s-sigstore-attestor pull request #30
Opened 2022-04-07 20:39 UTC by rodrigolc

**Pull Request check list**

- [ ] Commit conforms to CONTRIBUTING.md?
- [ ] Proper tests/regressions included?
- [ ] Documentation updated?

**Affected functionality**

**Description of change**

**Which issue this PR fixes**

2022-04-14 13:51 UTC, tjamir requested changes

2022-04-14 13:51 UTC, tjamir commented on support/k8s/k8s-workload-registrar/mode-crd/controllers/pod_controller_test.go
> +			CheckSignatureEnabled: true,
We could add a check if the selector sigstore passed is set.

2022-04-14 13:51 UTC, tjamir commented on support/k8s/k8s-workload-registrar/mode-reconcile/controllers/pod_controller_test.go
> +				true,
We could add a check if the selector sigstore passed is set.

2022-04-25 12:30 UTC, willallves approved these changes

2022-04-27 18:57 UTC, matheusdefarias approved these changes

2022-04-27 21:04 UTC, willallves approved these changes

2022-04-28 17:28 UTC, matheusdefarias approved these changes

2022-04-29 12:41 UTC, tjamir approved these changes

2022-04-29 13:19 UTC, merged